flags: {}
packages:
- '.'
extra-deps:
- distributed-process-0.5.5.1
- distributed-static-0.3.3.0
- distributed-process-simplelocalnet-0.2.3.1
- network-transport-tcp-0.4.2
- rank1dynamic-0.3.1.0
resolver: lts-3.1
